name: Deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to add comments to Pull Requests
  deployments: write # This is required to deactivate deployments

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"
  push:
    branches:
      - "main"
      - "deploy"
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  openidc:
    runs-on: ${{ vars.GH_RUNNER_TAG }} # define as an env var from UI for corresponding environment
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@master
        # uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.GH_OIDC_IAM_ROLE }}
          aws-region: us-east-1
          role-session-name: xom-role-session
          role-duration-seconds: 3600
          audience: sts.amazonaws.com

      - name: Check Current IAM Role
        run: aws sts get-caller-identity

  # deploy:
  #   name: Progressive Deployment
  #   uses: EMOrg-Prd/awsce-terraform-reusable-workflow/.github/workflows/terraform-reusable.yml@main
  #   strategy:
  #     max-parallel: 1
  #     fail-fast: true
  #     matrix:
  #       include:
  #         - environment: DEV-US-EAST-2
  #           region: us-east-2
  #         - environment: TST-US-EAST-2
  #           region: us-east-2
  #         - environment: PRD-US-EAST-2
  #           region: us-east-2
  #   with:
  #     deploy: true
  #     tf-version: ${{ vars.TF_VERSION }}
  #     tf-organization: ${{ vars.TF_ORGANIZATION }}
  #     tf-hostname: ${{ vars.TF_HOSTNAME }}
  #     tf-workspace: HP-AWS-${{ vars.APP_NAME }}-${{ matrix.environment }}
  #     aws-region: "us-east-2"
  #     environment: ${{ matrix.environment }}
  #   secrets:
  #     tf-token: ${{ secrets.TF_TOKEN }}
