name: Deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to add comments to Pull Requests
  deployments: write # This is required to deactivate deployments

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"
  push:
    branches:
      - "main"
      - "deploy"
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  # openidc:
  #   runs-on: ${{ vars.GH_RUNNER_TAG }} # define as an env var from UI for corresponding environment
  #   environment: dev
  #   steps:
  #     - name: Configure AWS Creds
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         audience: sts.amazonaws.com
  #         aws-region: us-east-2
  #         role-to-assume: ${{ vars.GH_OIDC_IAM_ROLE }}
  #         role-session-name: xom-role-session
  #         role-duration-seconds: 3600

  #     - name: Check Current IAM Role
  #       run: aws sts get-caller-identity
  deploy:
    steps:
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-2
          role-to-assume: ${{ vars.GH_OIDC_IAM_ROLE }}
          role-session-name: xom-role-session
          role-duration-seconds: 3600
      - name: Progressive Deployment
        # uses: EMOrg-Prd/awsce-terraform-reusable-workflow/.github/workflows/terraform-reusable.yml@main
        uses: aws-samples/aws-terraform-reusable-workflow/.github/workflows/terraform-reusable.yml@v1.2.0
        strategy:
          max-parallel: 1
          fail-fast: true
          matrix:
            include:
              - environment: dev
                region: us-east-2
              # - environment: prd
              #   region: us-east-2
        with:
          deploy: true
          tf-version: ${{ vars.TF_VERSION }}
          tf-organization: ${{ vars.TF_ORGANIZATION }}
          tf-hostname: ${{ vars.TF_HOSTNAME }}
          tf-workspace: HP-AWS-${{ vars.APP_NAME }}-${{ matrix.environment }}
          aws-region: "us-east-2"
          environment: ${{ matrix.environment }}
          ref: v1.2.0
        secrets:
          tf-token: ${{ secrets.TF_TOKEN }}
