name: Terraform Format

permissions:
  contents: read # This is required for actions/checkout

on:
  workflow_dispatch:
  pull_request:

jobs:
  fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt recursive check
        continue-on-error: true
        run: terraform fmt -check -diff -recursive
